import { expect, test } from '@playwright/test';

const api = process.env.CATCHHOLE_E2E_API_BASE_URL;
const email = process.env.CATCHHOLE_PRIVATE_E2E_EMAIL;
const password = process.env.CATCHHOLE_PRIVATE_E2E_PASSWORD;
const workId = process.env.CATCHHOLE_CHARACTER_E2E_WORK_ID;
const characterId = process.env.CATCHHOLE_CHARACTER_E2E_CHARACTER_ID;

test('캐릭터 카드·종족 선택·개인 보관함 공유를 실제 서버에 연결한다', async ({ page, request }) => {
  test.skip(!api || !email || !password || !workId || !characterId, '격리된 로컬 캐릭터 이미지 fixture가 필요합니다.');
  test.setTimeout(120_000);
  const login = await request.post(`${api}/api/v1/auth/login`, { data: { email, password } });
  expect(login.ok()).toBeTruthy();
  const token = (await login.json()).data.accessToken;
  const headers = { Authorization: `Bearer ${token}` };
  const characterUrl = `${api}/api/v1/works/${workId}/characters/${characterId}`;
  const read = async () => (await (await request.get(characterUrl, { headers })).json()).data;
  const setting = await request.post(`${api}/api/v1/works/${workId}/world-settings`, { headers,
    data: { category: 'RACE', subjectName: '공유 이미지 검증', settingName: '특징', settingValue: '개인 그림 공유' } });
  expect(setting.ok()).toBeTruthy();
  const settingId = (await setting.json()).data.id;
  await page.goto('/login');
  await page.evaluate(value => localStorage.setItem('accessToken', value), token);
  await page.goto(`/dashboard?workId=${workId}&nav=settingDB&tab=characters`);
  const card = page.getByRole('button', { name: '이름만 있는 인물 캐릭터 상세 보기', exact: true });
  await expect(card).toBeVisible();
  await expect(card).toContainText('첫 등장 회차 미확인');
  await expect(card).not.toContainText('CHARACTER');
  await expect(card).not.toContainText('대표 설정');
  await expect(card.locator('img')).toHaveJSProperty('naturalWidth', 640);
  expect(Math.round((await card.boundingBox())!.height)).toBe(177);
  await expect(page.locator('.app-route-layer')).toHaveCSS('opacity', '1');
  await page.screenshot({ path: 'docs/screens/gh194/character-images-desktop.png', animations: 'disabled' });
  await page.setViewportSize({ width: 320, height: 740 });
  await expect(card).toBeVisible();
  expect(Math.round((await card.boundingBox())!.height)).toBe(177);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: 'docs/screens/gh194/character-images-mobile.png', animations: 'disabled' });
  await page.setViewportSize({ width: 1280, height: 800 });
  await card.click();
  const detail = page.getByRole('dialog', { name: '이름만 있는 인물 캐릭터 상세', exact: true });
  await detail.getByRole('button', { name: '이미지 변경', exact: true }).click();
  const picker = page.getByRole('dialog', { name: '대표 이미지 선택', exact: true });
  await expect(page).toHaveURL(/mode=image/);
  await picker.getByLabel('대표 이미지 이름·별칭 검색').fill('고블린');
  await picker.getByRole('button', { name: '검색', exact: true }).click();
  await picker.getByRole('button', { name: '고블린 이미지 선택', exact: true }).click();
  await picker.getByRole('button', { name: '이미지 저장', exact: true }).click();
  await expect(picker).toHaveCount(0);
  expect((await read()).image).toMatchObject({ source: 'MANUAL', catalogId: 'race-goblin', version: 1 });
  // A stale image edit must retain the proposed selection until the user reloads explicitly.
  await detail.getByRole('button', { name: '이미지 변경', exact: true }).click();
  await picker.getByRole('button', { name: /^공통 기본 이미지/ }).click();
  expect((await request.patch(characterUrl + '/image', { headers, data: { version: 1, catalogId: 'race-elf' } })).ok()).toBeTruthy();
  await picker.getByRole('button', { name: '이미지 저장', exact: true }).click();
  await expect(picker.getByRole('alert')).toBeVisible();
  await expect(picker.getByRole('button', { name: /^공통 기본 이미지/ })).toHaveAttribute('aria-pressed', 'true');
  await picker.getByRole('button', { name: '최신 이미지 확인', exact: true }).click();
  await picker.getByRole('button', { name: '이미지 저장', exact: true }).click();
  await expect(picker).toHaveCount(0);
  expect((await read()).image).toMatchObject({ source: 'DEFAULT', version: 3 });
  await detail.getByRole('button', { name: '이미지 변경', exact: true }).click();
  await picker.getByRole('button', { name: /종족 정보에 따라 자동 선택/ }).click();
  await picker.getByRole('button', { name: '이미지 저장', exact: true }).click();
  await expect(picker).toHaveCount(0);
  expect((await read()).image).toMatchObject({ source: 'AUTO', catalogId: null, version: 4 });
  await detail.getByRole('button', { name: '이미지 변경', exact: true }).click();
  await page.reload();
  await expect(picker).toBeVisible();
  await picker.getByRole('button', { name: '내 이미지', exact: true }).click();
  await picker.getByRole('button', { name: '내 이미지 시작하기', exact: true }).click();
  const recoveryKey = await picker.getByLabel('내 보관용 코드', { exact: true }).inputValue();
  await picker.getByRole('checkbox').check();
  await picker.getByRole('button', { name: '보관함 사용하기', exact: true }).click();
  await picker.getByLabel('내 이미지 파일 선택').setInputFiles('src/assets/characters/character-neutral-v1.webp');
  await expect(picker.getByRole('button', { name: 'character-neutral-v1.webp 이미지 선택', exact: true }).locator('img')).toHaveJSProperty('naturalWidth', 480);
  await picker.getByRole('button', { name: '이미지 저장', exact: true }).click();
  await expect(picker).toHaveCount(0);
  const chosen = (await read()).image;
  expect(chosen.source).toBe('PRIVATE');
  const cipher = await request.get(`${api}${chosen.imageUrl}`, { headers });
  expect((await cipher.body()).subarray(0, 4).toString()).toBe('CHI1');
  expect(cipher.headers()['cache-control']).toContain('no-store');
  await expect(detail.locator('.character-detail-image img')).toHaveJSProperty('naturalWidth', 640);
  await page.setViewportSize({ width: 320, height: 740 });
  await page.screenshot({ path: 'docs/screens/gh194/character-private-image-mobile.png', animations: 'disabled' });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.reload();
  await expect(detail.locator('.character-detail-image')).toContainText('잠긴 내 이미지');
  await detail.getByRole('button', { name: '이미지 변경', exact: true }).click();
  await picker.getByLabel('보관용 코드', { exact: true }).fill(recoveryKey);
  await picker.getByRole('button', { name: '잠금 풀기', exact: true }).click();
  await expect(picker.getByRole('button', { name: 'character-neutral-v1.webp 이미지 선택', exact: true })).toBeVisible();
  await picker.getByRole('button', { name: '취소', exact: true }).click();
  // Same browser session and work: no second vault or duplicate upload.
  await page.goto(`/dashboard?workId=${workId}&nav=settingDB&tab=worldsettings&category=RACE&settingId=${settingId}`);
  await page.getByRole('button', { name: '이미지 변경', exact: true }).click();
  await picker.getByRole('button', { name: '내 이미지', exact: true }).click();
  // A full navigation intentionally locks the memory-only key.
  await picker.getByLabel('보관용 코드', { exact: true }).fill(recoveryKey);
  await picker.getByRole('button', { name: '잠금 풀기', exact: true }).click();
  await picker.getByRole('button', { name: 'character-neutral-v1.webp 이미지 선택', exact: true }).click();
  await picker.getByRole('button', { name: '이미지 저장', exact: true }).click();
  await expect(picker).toHaveCount(0);
  const world = (await (await request.get(`${api}/api/v1/works/${workId}/world-settings/${settingId}`, { headers })).json()).data;
  expect(world.image.privateImageId).toBe(chosen.privateImageId);
  expect((await request.delete(`${api}/api/v1/works/${workId}/private-world-images/${chosen.privateImageId}`, { headers })).status()).toBe(409);
});
